import requests
import json
import pandas as pd

# Your API endpoint
url = "https://api.sse.cisco.com/reports/v2/remote-access-events?to=now&limit=100&from=-1days"

# Your headers with the authorization token

headers = {
  'Authorization': 'Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjcyNmI5MGUzLWQ1MjYtNGMzZS1iN2QzLTllYjA5NWU2ZWRlOSIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ1bWJyZWxsYS1hdXRoei9hdXRoc3ZjIiwic3ViIjoib3JnLzgyNDI3MzEvY2xpZW50L2M0MWJjZmIxZTRhMDQ3NTVhYzY4OWNmMWRmNTY0NjNmIiwiZXhwIjoxNzIxMTMxOTkwLCJuYmYiOjE3MjExMjgzOTAsImlhdCI6MTcyMTEyODM5MCwic2NvcGUiOiJyZXBvcnRzLmdyYW51bGFyZXZlbnRzOnJlYWQgcmVwb3J0cy51dGlsaXRpZXM6cmVhZCByZXBvcnRzLmFnZ3JlZ2F0aW9uczp3cml0ZSByZXBvcnRzLmFnZ3JlZ2F0aW9uczpyZWFkIHJlcG9ydHMubWFsd2FyZTp3cml0ZSByZXBvcnRzLm1hbHdhcmU6cmVhZCByZXBvcnRzLmN1c3RvbWVyczp3cml0ZSByZXBvcnRzLmN1c3RvbWVyczpyZWFkIHJlcG9ydHMuYXBwZGlzY292ZXJ5OndyaXRlIHJlcG9ydHMuYXBwZGlzY292ZXJ5OnJlYWQgcmVwb3J0cy5hcGl1c2FnZTpyZWFkIHJlcG9ydHMudXNhZ2UuaW5nZXN0OndyaXRlIHJlcG9ydHMudXNhZ2UubWV0cmljczpyZWFkIHJlcG9ydHMudXNhZ2Uuc3RhdHVzOnJlYWQgcmVwb3J0cy5wcml2YXRlcmVzb3VyY2VzOnJlYWQgcmVwb3J0cy5zdW1tYXJpZXNieXJ1bGU6cmVhZCBpbnZlc3RpZ2F0ZS5pbnZlc3RpZ2F0ZTpyZWFkIGludmVzdGlnYXRlLmJ1bGs6cmVhZCBhZG1pbi51c2Vyczp3cml0ZSBhZG1pbi51c2VyczpyZWFkIGFkbWluLnJvbGVzOnJlYWQgYWRtaW4ub3JnYW5pemF0aW9uczp3cml0ZSBhZG1pbi5vcmdhbml6YXRpb25zOnJlYWQgYWRtaW4ucGFzc3dvcmRyZXNldDp3cml0ZSBhZG1pbi5jbG91ZGFwcGxpY2F0aW9uaW5zdGFuY2VzOndyaXRlIGFkbWluLmNsb3VkYXBwbGljYXRpb25pbnN0YW5jZXM6cmVhZCBkZXBsb3ltZW50cy5uZXR3b3Jrczp3cml0ZSBkZXBsb3ltZW50cy5uZXR3b3JrczpyZWFkIGRlcGxveW1lbnRzLnJvYW1pbmdjb21wdXRlcnM6d3JpdGUgZGVwbG95bWVudHMucm9hbWluZ2NvbXB1dGVyczpyZWFkIGRlcGxveW1lbnRzLmludGVybmFsbmV0d29ya3M6d3JpdGUgZGVwbG95bWVudHMuaW50ZXJuYWxuZXR3b3JrczpyZWFkIGRlcGxveW1lbnRzLmludGVybmFsZG9tYWluczp3cml0ZSBkZXBsb3ltZW50cy5pbnRlcm5hbGRvbWFpbnM6cmVhZCBkZXBsb3ltZW50cy52aXJ0dWFsYXBwbGlhbmNlczp3cml0ZSBkZXBsb3ltZW50cy52aXJ0dWFsYXBwbGlhbmNlczpyZWFkIGRlcGxveW1lbnRzLnNpdGVzOndyaXRlIGRlcGxveW1lbnRzLnNpdGVzOnJlYWQgZGVwbG95bWVudHMuZGF0YWNlbnRlcnM6cmVhZCBkZXBsb3ltZW50cy50dW5uZWxzOndyaXRlIGRlcGxveW1lbnRzLnR1bm5lbHM6cmVhZCBkZXBsb3ltZW50cy5uZXR3b3JrZGV2aWNlczp3cml0ZSBkZXBsb3ltZW50cy5uZXR3b3JrZGV2aWNlczpyZWFkIGRlcGxveW1lbnRzLnBvbGljaWVzOndyaXRlIGRlcGxveW1lbnRzLnBvbGljaWVzOnJlYWQgZGVwbG95bWVudHMubmV0d29ya3R1bm5lbGdyb3Vwczp3cml0ZSBkZXBsb3ltZW50cy5uZXR3b3JrdHVubmVsZ3JvdXBzOnJlYWQgZGVwbG95bWVudHMucmVnaW9uczpyZWFkIGRlcGxveW1lbnRzLmNvbm5lY3RvcmFnZW50OndyaXRlIGRlcGxveW1lbnRzLmlkZW50aXRpZXM6d3JpdGUgZGVwbG95bWVudHMuaWRlbnRpdGllczpyZWFkIGRlcGxveW1lbnRzLnRhZ2RldmljZXM6d3JpdGUgZGVwbG95bWVudHMudGFnZGV2aWNlczpyZWFkIGRlcGxveW1lbnRzLnRhZ3M6d3JpdGUgZGVwbG95bWVudHMudGFnczpyZWFkIHBvbGljaWVzLmRlc3RpbmF0aW9ubGlzdHM6d3JpdGUgcG9saWNpZXMuZGVzdGluYXRpb25saXN0czpyZWFkIHBvbGljaWVzLmRlc3RpbmF0aW9uczp3cml0ZSBwb2xpY2llcy5kZXN0aW5hdGlvbnM6cmVhZCBwb2xpY2llcy5kbHBpbmRleGVyOndyaXRlIHBvbGljaWVzLmRscGluZGV4ZXI6cmVhZCBwb2xpY2llcy5ydWxlczp3cml0ZSBwb2xpY2llcy5ydWxlczpyZWFkIHBvbGljaWVzLnByaXZhdGVyZXNvdXJjZWdyb3Vwczp3cml0ZSBwb2xpY2llcy5wcml2YXRlcmVzb3VyY2Vncm91cHM6cmVhZCBwb2xpY2llcy5wcml2YXRlcmVzb3VyY2VzOndyaXRlIHBvbGljaWVzLnByaXZhdGVyZXNvdXJjZXM6cmVhZCBwb2xpY2llcy5hcHByaXNrcHJvZmlsZW1hbmFnZXI6d3JpdGUgcG9saWNpZXMuYXBwcmlza3Byb2ZpbGVtYW5hZ2VyOnJlYWQgcG9saWNpZXMuYXBwbGljYXRpb25saXN0czp3cml0ZSBwb2xpY2llcy5hcHBsaWNhdGlvbmxpc3RzOnJlYWQgcG9saWNpZXMuc2V0dGluZ3M6d3JpdGUgcG9saWNpZXMuc2V0dGluZ3M6cmVhZCIsImF1dGh6X2RvbmUiOmZhbHNlfQ.QLbdieNYjlyrDMqDtW-2-yJzr4M_CbxNGF2MPC8xamMbjNPLhnbH9cqweKYWbp2Iy0yA4Z_quUx5EKP4Xm--WbugzvTGRFrtLUQ2_4A7f8v6nyDyN7qZSzAcTdYU67nWc_Lcrc9l2pbjFqRFt-c-Nb74n1Y30ZJ-WTier-g0ZXyBwTcpOBl3aoXBN3TW-5h-PbhRX7hIGdd8g9TwRzmtpRPuRwgbvu0xMhYnMdALxKlYpW1oULk-6XgvnN-nlLzx8q7SLPfYmexGsU7nftGYEztCx_LWdk-PdIX5AJksXYtk-IUtKoFoYNaAGKEhfPEkOpemU-n2AnK3v9kDM8z9BA'
}


# Make the GET request
response = requests.get(url, headers=headers)

# Check if the request was successful
if response.status_code == 200:
    # Convert the JSON response to a dictionary
    data_dict = json.loads(response.text)

    # Assuming the JSON data has a key 'data' that contains the records
    if 'data' in data_dict:
        # Convert the 'data' to a DataFrame
        df = pd.DataFrame(data_dict['data'])

        # Save the DataFrame to an Excel file
        df.to_excel('remote_access_events.xlsx', index=False)

        print("JSON data has been successfully converted to Excel and saved as 'remote_access_events.xlsx'.")
    else:
        print("The JSON response does not contain the 'data' key.")
else:
    print(f"Failed to fetch data, status code: {response.status_code}")

